/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen
Date:			12/9/2017
Description:	Creates the customer table and respective stored procedures

*/


USE applicationtemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `applicationtemplate`.`customer`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_customer_Load`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_customer_LoadAll`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_customer_Add`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_customer_Update`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_customer_Delete`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_customer_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `applicationtemplate`.`customer` (
Id INT AUTO_INCREMENT,
FirstName VARCHAR(255),
LastName VARCHAR(255),
Email VARCHAR(255),
Password VARCHAR(255),
CreateDate DATETIME,
CONSTRAINT pk_customer_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_customer_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`customer`.`Id` AS `Id`,
		`customer`.`FirstName` AS `FirstName`,
		`customer`.`LastName` AS `LastName`,
		`customer`.`Email` AS `Email`,
		`customer`.`Password` AS `Password`,
		`customer`.`CreateDate` AS `CreateDate`
	FROM `customer`
	WHERE 		`customer`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_customer_LoadAll`
()
BEGIN
	SELECT
		`customer`.`Id` AS `Id`,
		`customer`.`FirstName` AS `FirstName`,
		`customer`.`LastName` AS `LastName`,
		`customer`.`Email` AS `Email`,
		`customer`.`Password` AS `Password`,
		`customer`.`CreateDate` AS `CreateDate`
	FROM `customer`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_customer_Add`
(
	 IN paramFirstName VARCHAR(255),
	 IN paramLastName VARCHAR(255),
	 IN paramEmail VARCHAR(255),
	 IN paramPassword VARCHAR(255),
	 IN paramCreateDate DATETIME
)
BEGIN
	INSERT INTO `customer` (FirstName,LastName,Email,Password,CreateDate)
	VALUES (paramFirstName, paramLastName, paramEmail, paramPassword, paramCreateDate);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_customer_Update`
(
	IN paramId INT,
	IN paramFirstName VARCHAR(255),
	IN paramLastName VARCHAR(255),
	IN paramEmail VARCHAR(255),
	IN paramPassword VARCHAR(255),
	IN paramCreateDate DATETIME
)
BEGIN
	UPDATE `customer`
	SET FirstName = paramFirstName
		,LastName = paramLastName
		,Email = paramEmail
		,Password = paramPassword
		,CreateDate = paramCreateDate
	WHERE		`customer`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_customer_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `customer`
	WHERE		`customer`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_customer_Search`
(
	IN paramId INT,
	IN paramFirstName VARCHAR(255),
	IN paramLastName VARCHAR(255),
	IN paramEmail VARCHAR(255),
	IN paramPassword VARCHAR(255),
	IN paramCreateDate DATETIME
)
BEGIN
	SELECT
		`customer`.`Id` AS `Id`,
		`customer`.`FirstName` AS `FirstName`,
		`customer`.`LastName` AS `LastName`,
		`customer`.`Email` AS `Email`,
		`customer`.`Password` AS `Password`,
		`customer`.`CreateDate` AS `CreateDate`
	FROM `customer`
	WHERE
		COALESCE(customer.`Id`,0) = COALESCE(paramId,customer.`Id`,0)
		AND COALESCE(customer.`FirstName`,'') = COALESCE(paramFirstName,customer.`FirstName`,'')
		AND COALESCE(customer.`LastName`,'') = COALESCE(paramLastName,customer.`LastName`,'')
		AND COALESCE(customer.`Email`,'') = COALESCE(paramEmail,customer.`Email`,'')
		AND COALESCE(customer.`Password`,'') = COALESCE(paramPassword,customer.`Password`,'')
		AND COALESCE(CAST(customer.`CreateDate` AS DATE), CAST(NOW() AS DATE)) = COALESCE(CAST(paramCreateDate AS DATE),CAST(customer.`CreateDate` AS DATE), CAST(NOW() AS DATE));
END //
DELIMITER ;


/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen
Date:			12/9/2017
Description:	Creates the statustype table and respective stored procedures

*/


USE applicationtemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `applicationtemplate`.`statustype`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_statustype_Load`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_statustype_LoadAll`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_statustype_Add`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_statustype_Update`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_statustype_Delete`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_statustype_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `applicationtemplate`.`statustype` (
Id INT AUTO_INCREMENT,
Name VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_statustype_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_statustype_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`statustype`.`Id` AS `Id`,
		`statustype`.`Name` AS `Name`,
		`statustype`.`Description` AS `Description`
	FROM `statustype`
	WHERE 		`statustype`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_statustype_LoadAll`
()
BEGIN
	SELECT
		`statustype`.`Id` AS `Id`,
		`statustype`.`Name` AS `Name`,
		`statustype`.`Description` AS `Description`
	FROM `statustype`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_statustype_Add`
(
	 IN paramName VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `statustype` (Name,Description)
	VALUES (paramName, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_statustype_Update`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `statustype`
	SET Name = paramName
		,Description = paramDescription
	WHERE		`statustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_statustype_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `statustype`
	WHERE		`statustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_statustype_Search`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`statustype`.`Id` AS `Id`,
		`statustype`.`Name` AS `Name`,
		`statustype`.`Description` AS `Description`
	FROM `statustype`
	WHERE
		COALESCE(statustype.`Id`,0) = COALESCE(paramId,statustype.`Id`,0)
		AND COALESCE(statustype.`Name`,'') = COALESCE(paramName,statustype.`Name`,'')
		AND COALESCE(statustype.`Description`,'') = COALESCE(paramDescription,statustype.`Description`,'');
END //
DELIMITER ;


/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen
Date:			12/9/2017
Description:	Creates the role table and respective stored procedures

*/


USE applicationtemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `applicationtemplate`.`role`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_role_Load`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_role_LoadAll`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_role_Add`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_role_Update`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_role_Delete`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_role_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `applicationtemplate`.`role` (
Id INT AUTO_INCREMENT,
Name VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_role_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_role_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`role`.`Id` AS `Id`,
		`role`.`Name` AS `Name`,
		`role`.`Description` AS `Description`
	FROM `role`
	WHERE 		`role`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_role_LoadAll`
()
BEGIN
	SELECT
		`role`.`Id` AS `Id`,
		`role`.`Name` AS `Name`,
		`role`.`Description` AS `Description`
	FROM `role`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_role_Add`
(
	 IN paramName VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `role` (Name,Description)
	VALUES (paramName, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_role_Update`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `role`
	SET Name = paramName
		,Description = paramDescription
	WHERE		`role`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_role_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `role`
	WHERE		`role`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_role_Search`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`role`.`Id` AS `Id`,
		`role`.`Name` AS `Name`,
		`role`.`Description` AS `Description`
	FROM `role`
	WHERE
		COALESCE(role.`Id`,0) = COALESCE(paramId,role.`Id`,0)
		AND COALESCE(role.`Name`,'') = COALESCE(paramName,role.`Name`,'')
		AND COALESCE(role.`Description`,'') = COALESCE(paramDescription,role.`Description`,'');
END //
DELIMITER ;


/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen
Date:			12/9/2017
Description:	Creates the securityuser table and respective stored procedures

*/


USE applicationtemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `applicationtemplate`.`securityuser`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_securityuser_Load`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_securityuser_LoadAll`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_securityuser_Add`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_securityuser_Update`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_securityuser_Delete`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_securityuser_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `applicationtemplate`.`securityuser` (
Id INT AUTO_INCREMENT,
Username VARCHAR(255),
Password VARCHAR(255),
Email VARCHAR(255),
RoleId INT,
CreateDate DATETIME,
CONSTRAINT pk_securityuser_Id PRIMARY KEY (Id),
CONSTRAINT fk_securityuser_RoleId_Role_Id FOREIGN KEY (RoleId) REFERENCES Role (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_securityuser_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`securityuser`.`Id` AS `Id`,
		`securityuser`.`Username` AS `Username`,
		`securityuser`.`Password` AS `Password`,
		`securityuser`.`Email` AS `Email`,
		`securityuser`.`RoleId` AS `RoleId`,
		`securityuser`.`CreateDate` AS `CreateDate`
	FROM `securityuser`
	WHERE 		`securityuser`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_securityuser_LoadAll`
()
BEGIN
	SELECT
		`securityuser`.`Id` AS `Id`,
		`securityuser`.`Username` AS `Username`,
		`securityuser`.`Password` AS `Password`,
		`securityuser`.`Email` AS `Email`,
		`securityuser`.`RoleId` AS `RoleId`,
		`securityuser`.`CreateDate` AS `CreateDate`
	FROM `securityuser`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_securityuser_Add`
(
	 IN paramUsername VARCHAR(255),
	 IN paramPassword VARCHAR(255),
	 IN paramEmail VARCHAR(255),
	 IN paramRoleId INT,
	 IN paramCreateDate DATETIME
)
BEGIN
	INSERT INTO `securityuser` (Username,Password,Email,RoleId,CreateDate)
	VALUES (paramUsername, paramPassword, paramEmail, paramRoleId, paramCreateDate);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_securityuser_Update`
(
	IN paramId INT,
	IN paramUsername VARCHAR(255),
	IN paramPassword VARCHAR(255),
	IN paramEmail VARCHAR(255),
	IN paramRoleId INT,
	IN paramCreateDate DATETIME
)
BEGIN
	UPDATE `securityuser`
	SET Username = paramUsername
		,Password = paramPassword
		,Email = paramEmail
		,RoleId = paramRoleId
		,CreateDate = paramCreateDate
	WHERE		`securityuser`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_securityuser_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `securityuser`
	WHERE		`securityuser`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_securityuser_Search`
(
	IN paramId INT,
	IN paramUsername VARCHAR(255),
	IN paramPassword VARCHAR(255),
	IN paramEmail VARCHAR(255),
	IN paramRoleId INT,
	IN paramCreateDate DATETIME
)
BEGIN
	SELECT
		`securityuser`.`Id` AS `Id`,
		`securityuser`.`Username` AS `Username`,
		`securityuser`.`Password` AS `Password`,
		`securityuser`.`Email` AS `Email`,
		`securityuser`.`RoleId` AS `RoleId`,
		`securityuser`.`CreateDate` AS `CreateDate`
	FROM `securityuser`
	WHERE
		COALESCE(securityuser.`Id`,0) = COALESCE(paramId,securityuser.`Id`,0)
		AND COALESCE(securityuser.`Username`,'') = COALESCE(paramUsername,securityuser.`Username`,'')
		AND COALESCE(securityuser.`Password`,'') = COALESCE(paramPassword,securityuser.`Password`,'')
		AND COALESCE(securityuser.`Email`,'') = COALESCE(paramEmail,securityuser.`Email`,'')
		AND COALESCE(securityuser.`RoleId`,0) = COALESCE(paramRoleId,securityuser.`RoleId`,0)
		AND COALESCE(CAST(securityuser.`CreateDate` AS DATE), CAST(NOW() AS DATE)) = COALESCE(CAST(paramCreateDate AS DATE),CAST(securityuser.`CreateDate` AS DATE), CAST(NOW() AS DATE));
END //
DELIMITER ;


/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen
Date:			12/9/2017
Description:	Creates the cart table and respective stored procedures

*/


USE applicationtemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `applicationtemplate`.`cart`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_cart_Load`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_cart_LoadAll`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_cart_Add`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_cart_Update`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_cart_Delete`;
DROP PROCEDURE IF EXISTS `applicationtemplate`.`usp_cart_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `applicationtemplate`.`cart` (
Id INT AUTO_INCREMENT,
CustomerId INT,
StatusTypeId INT,
CreateDate DATETIME,
CheckoutDate DATETIME,
CONSTRAINT pk_cart_Id PRIMARY KEY (Id),
CONSTRAINT fk_cart_CustomerId_customer_Id FOREIGN KEY (CustomerId) REFERENCES customer (Id),
CONSTRAINT fk_cart_StatusTypeId_statustype_Id FOREIGN KEY (StatusTypeId) REFERENCES statustype (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_cart_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`cart`.`Id` AS `Id`,
		`cart`.`CustomerId` AS `CustomerId`,
		`cart`.`StatusTypeId` AS `StatusTypeId`,
		`cart`.`CreateDate` AS `CreateDate`,
		`cart`.`CheckoutDate` AS `CheckoutDate`
	FROM `cart`
	WHERE 		`cart`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_cart_LoadAll`
()
BEGIN
	SELECT
		`cart`.`Id` AS `Id`,
		`cart`.`CustomerId` AS `CustomerId`,
		`cart`.`StatusTypeId` AS `StatusTypeId`,
		`cart`.`CreateDate` AS `CreateDate`,
		`cart`.`CheckoutDate` AS `CheckoutDate`
	FROM `cart`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_cart_Add`
(
	 IN paramCustomerId INT,
	 IN paramStatusTypeId INT,
	 IN paramCreateDate DATETIME,
	 IN paramCheckoutDate DATETIME
)
BEGIN
	INSERT INTO `cart` (CustomerId,StatusTypeId,CreateDate,CheckoutDate)
	VALUES (paramCustomerId, paramStatusTypeId, paramCreateDate, paramCheckoutDate);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_cart_Update`
(
	IN paramId INT,
	IN paramCustomerId INT,
	IN paramStatusTypeId INT,
	IN paramCreateDate DATETIME,
	IN paramCheckoutDate DATETIME
)
BEGIN
	UPDATE `cart`
	SET CustomerId = paramCustomerId
		,StatusTypeId = paramStatusTypeId
		,CreateDate = paramCreateDate
		,CheckoutDate = paramCheckoutDate
	WHERE		`cart`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_cart_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `cart`
	WHERE		`cart`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_cart_Search`
(
	IN paramId INT,
	IN paramCustomerId INT,
	IN paramStatusTypeId INT,
	IN paramCreateDate DATETIME,
	IN paramCheckoutDate DATETIME
)
BEGIN
	SELECT
		`cart`.`Id` AS `Id`,
		`cart`.`CustomerId` AS `CustomerId`,
		`cart`.`StatusTypeId` AS `StatusTypeId`,
		`cart`.`CreateDate` AS `CreateDate`,
		`cart`.`CheckoutDate` AS `CheckoutDate`
	FROM `cart`
	WHERE
		COALESCE(cart.`Id`,0) = COALESCE(paramId,cart.`Id`,0)
		AND COALESCE(cart.`CustomerId`,0) = COALESCE(paramCustomerId,cart.`CustomerId`,0)
		AND COALESCE(cart.`StatusTypeId`,0) = COALESCE(paramStatusTypeId,cart.`StatusTypeId`,0)
		AND COALESCE(CAST(cart.`CreateDate` AS DATE), CAST(NOW() AS DATE)) = COALESCE(CAST(paramCreateDate AS DATE),CAST(cart.`CreateDate` AS DATE), CAST(NOW() AS DATE))
		AND COALESCE(CAST(cart.`CheckoutDate` AS DATE), CAST(NOW() AS DATE)) = COALESCE(CAST(paramCheckoutDate AS DATE),CAST(cart.`CheckoutDate` AS DATE), CAST(NOW() AS DATE));
END //
DELIMITER ;


use applicationtemplate;
DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_cart_LoadByCustomerId`
(
	 IN paramCustomerId INT
)
BEGIN
	SELECT DISTINCT
		`cart`.`Id` AS `Id`,
		`cart`.`CustomerId` AS `CustomerId`,
		`cart`.`StatusTypeId` AS `StatusTypeId`,
		`cart`.`CreateDate` AS `CreateDate`,
		`cart`.`CheckoutDate` AS `CheckoutDate`
	FROM `cart`
	WHERE 		`cart`.`CustomerId` = paramCustomerId
	AND `cart`.`StatusTypeId` = 4;  -- active cart
END //
DELIMITER ;

use applicationtemplate;
DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_customer_Lookup`
(
	IN paramEmail VARCHAR(255)
)
BEGIN
  SELECT
	  `customer`.`Id` AS `Id`,
		`customer`.`FirstName` AS `FirstName`,
		`customer`.`LastName` AS `LastName`,
		`customer`.`Email` AS `Email`,
		`customer`.`Password` AS `Password`,
		`customer`.`CreateDate` AS `CreateDate`
	FROM `customer`
	WHERE 		`customer`.`Email` = paramEmail;
END //
DELIMITER ;

use applicationtemplate;
DELIMITER //
CREATE PROCEDURE `applicationtemplate`.`usp_securityuser_Lookup`
(
	IN paramUsername VARCHAR(255)
)
BEGIN
  SELECT
			`securityuser`.`Id` AS `Id`,
		`securityuser`.`Username` AS `Username`,
		`securityuser`.`Password` AS `Password`,
		`securityuser`.`Email` AS `Email`,
		`securityuser`.`RoleId` AS `RoleId`,
		`securityuser`.`CreateDate` AS `CreateDate`
	FROM `securityuser`
	WHERE 		`securityuser`.`Username` = paramUsername;
END //
DELIMITER ;

use applicationtemplate;

INSERT INTO `statustype` (`Id`, `Name`, `Description`) VALUES (1, 'Active Item', 'Item will appear on site');
INSERT INTO `statustype` (`Id`, `Name`, `Description`) VALUES (2, 'Inactive Item', 'Item will not appear on site');
INSERT INTO `statustype` (`Id`, `Name`, `Description`) VALUES (3, 'On Sale Item', 'Item is on sale');
INSERT INTO `statustype` (`Id`, `Name`, `Description`) VALUES ('4', 'Active Cart', 'Cart has not been checkout and is recognized as active. We will not delete any active carts.');
INSERT INTO `statustype` (`Id`, `Name`, `Description`) VALUES ('5', 'Inactive Cart', 'Cart has been checked out or abandoned.');